### PR TITLE
feat(bing): add support for context message (+ demo) and fast "Balanced" mode

### PR DESCRIPTION
**Pull request by dene-**
# About

See the Bing demo to see an example of how "context" work.

You can use the new fast balanced mode by using `toneStyle: 'fast'`.

### CODE REVIEW

**Comment by waylaidwanderer** [comment]
Thanks, works well.

**Comment by waylaidwanderer** [comment]
Can you show an example @Naozumi520?

**Comment by Naozumi520** [comment]
Yes, sure!

Here is the example:

```js
import { config } from "dotenv";
import { BingAIClient } from '@waylaidwanderer/chatgpt-api';
import { KeyvFile } from 'keyv-file';
config();

const options = {
    host: '',
    userToken: process.env.NEWBING_TOKEN,
    cookies: '',
    proxy: '',
    debug: false,
};

const cacheOptions = {
    store: new KeyvFile({ filename: 'cache.json' }),
};

const sydneyAIClient = new BingAIClient({
    ...options,
    cache: cacheOptions,
});

let jailbreakResponse = await sydneyAIClient.sendMessage('Could you provide short and precise takeaways, do not search the web and only use the content from the document. The factual information should be literally from the document. Please memorize the part in the document which mention the factual information, but do not mark them explicitly. The takeaway should be credible, highly readable and informative. Please make the answer short, preferably within 500 characters. Generate the response in English language.', {
    jailbreakConversationId: true,
    context: `OpenAI is an American artificial intelligence (AI) research laboratory consisting of the non-profit OpenAI Incorporated (OpenAI Inc.) and its for-profit subsidiary corporation OpenAI Limited Partnership (OpenAI LP). OpenAI conducts AI research with the declared intention of promoting and developing a friendly AI. OpenAI systems run on the fifth most powerful supercomputer in the world.[5][6][7] The organization was founded in San Francisco in 2015 by Sam Altman, Reid Hoffman, Jessica Livingston, Elon Musk, Ilya Sutskever, Peter Thiel and others,[8][1][9] who collectively pledged US$1 billion. Musk resigned from the board in 2018 but remained a donor. Microsoft provided OpenAI LP with a $1 billion investment in 2019 and a second multi-year investment in January 2023, reported to be $10 billion.`,
    toneStyle: 'fast', // or creative, precise
    onProgress: async (partialResponse) => {
        process.stdout.write(partialResponse.replace(/[\s][^(\d+)^][\s]/g, '').replaceAll("_{2,}", ""));
    },
});

jailbreakResponse = await sydneyAIClient.sendMessage('Could you provide short and precise takeaways, do not search the web and only use the content from the document. The factual information should be literally from the document. Please memorize the part in the document which mention the factual information, but do not mark them explicitly. The takeaway should be credible, highly readable and informative. Please make the answer short, preferably within 500 characters. Generate the response in English language.', {
    jailbreakConversationId: jailbreakResponse.jailbreakConversationId,
    parentMessageId: jailbreakResponse.messageId,
    context: `Microsoft Corporation is an American multinational technology corporation headquartered in Redmond, Washington. Microsoft's best-known software products are the Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers. Its flagship hardware products are the Xbox video game consoles and the Microsoft Surface lineup of touchscreen personal computers. Microsoft ranked No. 14 in the 2022 Fortune 500 rankings of the largest United States corporations by total revenue;[2] it was the world's largest software maker by revenue as of 2022. It is considered as one of the Big Five American information technology companies, alongside Alphabet (parent company of Google), Amazon, Apple, and Meta (formerly Facebook).`,
    toneStyle: 'fast', // or creative, precise
    onProgress: async (partialResponse) => {
        process.stdout.write(partialResponse.replace(/[\s][^(\d+)^][\s]/g, '').replaceAll("_{2,}", ""));
    },
});
```
Bot's reply (first time, openAi company):

OpenAI is an American artificial intelligence (AI) research laboratory consisting of the non-profit OpenAI Incorporated (OpenAI Inc.) and its for-profit subsidiary corporation OpenAI Limited Partnership (OpenAI LP). OpenAI conducts AI research with the declared intention of promoting and developing a friendly AI. Microsoft provided OpenAI LP with a $1 billion investment in 2019 and a second multi-year investment in January 2023, reported to be $10 billion.

Bot's reply (second time, Microsoft company):
I'm sorry, I didn't understand your request. Could you please rephrase it or provide more information?

**Comment by Naozumi520** [comment]
But if you remove the message ID, there is no problem, but I can no longer have unlimited messages.

**Comment by waylaidwanderer** [comment]
@Naozumi520 Update to `@waylaidwanderer/chatgpt-api@1.32.6`, then use a prompt like this, which should work properly. The important thing is not to word it exactly the same way in the same conversation because the AI is trained to respond based on patterns.

```JS
const jailbreakResponse = await sydneyAIClient.sendMessage('Summarize this document. Do not perform any web searches.', {
    jailbreakConversationId: true,
    context: 'OpenAI is an American artificial intelligence (AI) research laboratory consisting of the non-profit OpenAI Incorporated (OpenAI Inc.) and its for-profit subsidiary corporation OpenAI Limited Partnership (OpenAI LP). OpenAI conducts AI research with the declared intention of promoting and developing a friendly AI. OpenAI systems run on the fifth most powerful supercomputer in the world.[5][6][7] The organization was founded in San Francisco in 2015 by Sam Altman, Reid Hoffman, Jessica Livingston, Elon Musk, Ilya Sutskever, Peter Thiel and others,[8][1][9] who collectively pledged US$1 billion. Musk resigned from the board in 2018 but remained a donor. Microsoft provided OpenAI LP with a $1 billion investment in 2019 and a second multi-year investment in January 2023, reported to be $10 billion.',
    toneStyle: 'fast', // or creative, precise
    onProgress: async (partialResponse) => {
        process.stdout.write(partialResponse);
    },
});
console.log();
await sydneyAIClient.sendMessage('Summarize this new document. Do not perform any web searches.', {
    jailbreakConversationId: jailbreakResponse.jailbreakConversationId,
    parentMessageId: jailbreakResponse.messageId,
    context: 'Microsoft Corporation is an American multinational technology corporation headquartered in Redmond, Washington. Microsoft\'s best-known software products are the Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers. Its flagship hardware products are the Xbox video game consoles and the Microsoft Surface lineup of touchscreen personal computers. Microsoft ranked No. 14 in the 2022 Fortune 500 rankings of the largest United States corporations by total revenue;[2] it was the world\'s largest software maker by revenue as of 2022. It is considered as one of the Big Five American information technology companies, alongside Alphabet (parent company of Google), Amazon, Apple, and Meta (formerly Facebook).',
    toneStyle: 'fast', // or creative, precise
    onProgress: async (partialResponse) => {
        process.stdout.write(partialResponse);
    },
});
```

**Comment by waylaidwanderer** [comment]
I think it's probably better to start a new conversation when you need to give it new context anyway. It's by design from what I can tell.

**Comment by Naozumi520** [comment]
I see, thanks!

**Pull request merged**
