### PR TITLE
feat(client): adding conversation overwrite, conversation return and keepNecessaryMessagesOnly features

### PR DESCRIPTION
**Pull request by Leask**
Adding some API options.

In `ChatGPTClient.constructor()`:
- The new `returnConversation` option will enable the `sendMessage` API to return the current conversation, not only the current response.
- The new `keepNecessaryMessagesOnly` option will trim the conversation to keep the latest part used to build future prompts.

In `ChatGPTClient.sendMessage()`:
- The new `conversation` option will overwrite the current conversation in the cache.

Why?
- With the `returnConversation` and `conversation` options working together, you can easily back up and restore the conversation. If someone is building a restartable service and does not want to adapt `keyv`, someone can also fork a conversation from others.
- The `keepNecessaryMessagesOnly` option will help us reduce total memory consumption when using the default in-memory `keyv` configuration.

### CODE REVIEW

**Comment by Leask** [comment]
Need some tweaks. Hold back.

**Comment by Leask** [comment]
I rewrote some code to make it more efficient. Please check it out!

**Comment by Leask** [comment]
Upgraded `ChatGPTCLient` to support different `system prompts` on-the-fly.

**Comment by waylaidwanderer** [comment]
@Leask ready for me to take a look?

**Comment by Leask** [comment]
> @Leask ready for me to take a look?

Sure! anytime! Thanks! 😄

**Comment by danny-avila** [comment]
This PR would be helpful, will it be merged @waylaidwanderer ?

**Comment by waylaidwanderer** [comment]
Looks good to me, thanks so much @Leask. Sorry about the delay.

**Comment by Leask** [comment]
🎉

**Pull request merged**
