### PR TITLE
fix(client): updated fastify host binding to support proper docker deployment

### LINKED ISSUE #3: Add Dockerfile so this can be run under Docker
This is a good reference and I know it works on both ARM64 and AMD64: https://github.com/matrixgpt/matrix-chatgpt-bot/blob/main/Dockerfile

### PR DESCRIPTION
**Pull request by queercat**
This will allow for a standalone Docker build. And is a part of attempting to resolve issue #3.
See my [repo](https://github.com/queercat/gpt-api-docker) that resolves #3 once this is resolved. 

The reason this isn't working is docker cannot support the 127.0.0.1 binding only 0.0.0.0 (which Fastify prefers anyway afaik.)

### CODE REVIEW

**Comment by queercat** [comment]
Running a curl to my locally running docker image.
https://asciinema.org/a/oMzmIgBV3A2gzbdH4tBIEwuHW

image

I will probably have to write the Dockerfile to modify the settings a little to read from an environment variable or .env but it should be relatively simple.

Let me know if you have any questions!

**Comment by queercat** [comment]
> I will probably have to write the Dockerfile to modify the settings a little to read from an environment variable or .env but it should be relatively simple.

This now works provided you merge #20. The only change needed to be made after that is changing the clone target from my modified repo to yours :)

**Comment by waylaidwanderer** [comment]
@queercat Thanks, but could you make the host configurable like the port? People may not want it to be exposed to the internet directly.

**Comment by waylaidwanderer** [comment]
Also if you want to add the dockerfile to the PR as well, that would be cool.

**Comment by waylaidwanderer** [comment]
Actually don't worry, I'll merge it in so you get contributor credit and then change it myself :D

**Pull request merged**
