### PR TITLE
feat(bing): put the conversation in "document summary" context

### PR DESCRIPTION
**Pull request by InterestingDarkness**
https://github.com/waylaidwanderer/node-chatgpt-api/issues/245
It passed "use-bing-client.js" test

### CODE REVIEW

**Comment by waylaidwanderer** [comment]
@InterestingDarkness thanks, I did a bunch of testing and it works well!

**Comment by MaKaiYi** [comment]
123

**Comment by Naozumi520** [comment]
@waylaidwanderer This update broke the context input. Any workarounds of it?

**Comment by InterestingDarkness** [comment]
> @waylaidwanderer This update broke the context input. Any workarounds of it? It will only return `Hello! How can I help you today?`

Can you show me your code? It passed "use-bing-client.js" test

**Comment by Naozumi520** [comment]
Here: https://github.com/waylaidwanderer/node-chatgpt-api/pull/216

I commented the examples and it's the same one :)

**Comment by InterestingDarkness** [comment]
OK I've found a fix

**Comment by InterestingDarkness** [comment]
https://github.com/waylaidwanderer/node-chatgpt-api/pull/256
This should work

**Pull request merged**
