### PR TITLE
feat(bing): add systemMessage

### LINKED ISSUE #178: Feature Request: systemMessage
Allow us to set the system message sent to Bing Chat! What if I want my chatbot to be named "Jake"?

### PR DESCRIPTION
**Pull request by Erisfiregamer1**
A very helpful feature for the bing AI client! systemMessage defines the message sent to Sydney/Bing Chat on jailbreak mode.

PLEASE tell me if something I did was wrong. This was just a quick PR and I didn't see anything wrong on a quick look at my code but I probably broke something.

Closes #178

### CODE REVIEW

**Comment by Erisfiregamer1** [comment]
Fixed conflicts, ready for merge

**Comment by Erisfiregamer1** [comment]
Ready for review @waylaidwanderer

**Comment by waylaidwanderer** [comment]
@Erisfiregamer1 Thanks for updating your PR. You should probably know that with the latest update, `system` type messages trigger the moderation filter, which caused the jailbreak to stop working, which is why I changed it to a bot message instead.

Because of this, you can't have a system message at all anymore, unfortunately.

**Comment by InterestingDarkness** [comment]
No, system message still works, but you need to insert some separator into "system additional instruction" like this
https://www.make-safe-ai.com/is-bing-chat-safe/

**Comment by Erisfiregamer1** [comment]
@waylaidwanderer I made systemMessage modify the bot message instead. Ready to merge :)

**Pull request merged**
