### PR TITLE
ChatGPTBrowserClient: Add generated title to response

### PR DESCRIPTION
**Pull request by danny-avila**
This is a simple proposed update but necessary for my app. 

This will add the officially generated title to the response object as a promise, which keeps the operation asynchronous and allows me to await `response.details.title` when I need it. Can be totally ignored by those who don't need it and should keep all other operations the same.

Thought this might be the simplest way to attach the title to a response, since it only generates on the first one.

Without this, I have to do a redundant call for a title since I know we make a request to the backend api. Not to mention, my own calls cost tokens (a few but they add up) and the official titling tends to perform better.

### CODE REVIEW

**Comment by danny-avila** [comment]
Ah looks like I'm failing a test specific to genTitle not returning anything. Let me know if you'd like to implement this and I may need to make a new PR anyway (didn't mean to add the extra commit)

**Comment by waylaidwanderer** [comment]
> Ah looks like I'm failing a test specific to genTitle not returning anything. Let me know if you'd like to implement this and I may need to make a new PR anyway (didn't mean to add the extra commit)

Sounds good to me, but you may also want to change ChatGPTClient's title to be async as well to match.

**Comment by danny-avila** [comment]
> Sounds good to me, but you may also want to change ChatGPTClient's title to be async as well to match.

It looks like the generateTitle in client is already async and is awaited as part of the response from the client when the option "shouldGenerateTitle" is set. I thought these two functions were fundamentally different since genTitle is not optional and makes the call to backend-api, otherwise the conversation shows up as 'New chat' on chat.openai.com. 

Would you like me to match how ChatGPTClient works and await the title within postConversation? Thing is, that gen_title call would be pretty blocking here, and I like how it already works,  but either way works for me. 

In any case, the test would still fail for me, because it expects genTitle not to return anything. I'll make another PR with just the one commit after your comments on this!

**Comment by waylaidwanderer** [comment]
I meant that `response.details.title` in `ChatGPTClient` could be a Promise as well. Currently, it's just the final string result. Then whatever calls `sendMessage()` can decide if they want the `title` value by calling `await` on it. This would be a slightly breaking change, of course, but that's fine. Does this make sense?

**Comment by waylaidwanderer** [comment]
Actually idk if that's even a good approach. On second thought, just make your one commit PR and I'll figure it out from there LOL

**Comment by danny-avila** [comment]
Got it, thanks! about to send the new one

**Pull request closed without merging**
