### PR TITLE
refactor: use fetch-undici instead of node-fetch

### PR DESCRIPTION
**Pull request by Songkeys**
Undici is a more modern, stable, performant fetch library.

### CODE REVIEW

**Comment by Songkeys** [comment]
It's a wrapper for https://github.com/nodejs/undici

**Comment by waylaidwanderer** [comment]
@Songkeys seems like a wrapper is unnecessary: https://github.com/nodejs/undici#undicifetchinput-init-promise

**Comment by waylaidwanderer** [comment]
I guess there is still a use-case for this, so nvm. I'll merge it in.

**Comment by Songkeys** [comment]
There was some node-specific api used in undici that will result in conflicts in browser env. That's why this wrapper package exists (https://github.com/bcomnes/fetch-undici/blob/e7e622793d9063539fdf5753d0e0b0f1d4a248d1/package.json#L25-L28).

But I think I got it wrong cuz after taking another look, this package actually is not browser-compatible actaully (e.g. the use of "crypto", "keyV", "gpt-3-encoder"). I think the original undici package should be enough if so.

**Comment by waylaidwanderer** [comment]
I'll look into the browser compatibility aspect of this project in the near future.

**Pull request merged**
