### PR TITLE
add ChatGPTBox to Projects

### PR DESCRIPTION
**Pull request by josStorer**

### CODE REVIEW

**Comment by waylaidwanderer** [comment]
Can you explain where it uses `@waylaidwanderer/chatgpt-api`? It's not listed in https://github.com/josStorer/chatGPTBox/blob/master/package.json

**Comment by josStorer** [comment]
@waylaidwanderer 
Sorry for my insufficient description. I use the Bing client of this repo, but since my project is a browser extension, I made some adjustments to make it run in the browser. However, most of the code still comes from this repo. Here is the referenced file:
https://github.com/josStorer/chatGPTBox/blob/master/src/background/clients/BingAIClient.js

**Comment by waylaidwanderer** [comment]
Ah, okay, I see now. Thank you for explaining!

**Comment by TovovoT** [comment]
你好，大神，有款开源的笔记软件“joplin”很好用，是否可以把chatbox集成到joplin的插件里，特别期待！https://github.com/laurent22/joplin/

**Pull request merged**
