### PR TITLE
feat(bing): jailbreak redux

### LINKED ISSUE #202: Error: Unexpected server response: 502
- I am using bing jailbreak mode (Sydney) and stream=true.
- For the node-chatgpt-api version, I am using the latest version by git clone.
- I am running an api server using docker.

The following problem occurs **intermittently**.

It works fine for a while, but suddenly an error occurs.
I've tested it several times, but I don't know under what circumstances it happens.

```
Error: Unexpected server response: 502
disconnected
    at ClientRequest.<anonymous> (/var/chatgpt-api/node_modules/ws/lib/websocket.js:888:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

My client side code is below. I'll add it in case it might be helpful.

```
async with aiohttp.ClientSession() as session:
        async with session.post(url, json=payload) as resp:
            if resp.status == 200:
                async for line in resp.content:
                    ......
```

If this is a microsoft server side problem, I would appreciate it if you could throw an exception on this. Right now handling the exception on the client doesn't solve the problem until I restart the api server.

### LINKED ISSUE #203: Updated moderation filter?
I keep getting errors from the content moderation filter. It worked fine a few hours ago, but now I just get a bunch of errors triggering moderation filter. Is it my injected prompt had failed somehow or are people receiving this as well?

### PR DESCRIPTION
**Pull request by waylaidwanderer**
- update jailbreak, closes #203
- throw an error in `sendMessage()` when websocket error occurs, fixes #202

### CODE REVIEW

**Comment by yuwangi** [comment]
I tried, but it still doesn't work，whether the configuration has need modified？

**Comment by waylaidwanderer** [comment]
@yuwangi I'm gonna need more details than "still doesn't work"

**Comment by yuwangi** [comment]
Update dependencies to  1.31.0 ,doesn't work  
image

**Comment by waylaidwanderer** [comment]
If you're running in Docker you need to rebuild the container.

**Comment by KevinKaiwenZheng** [comment]
I think it has some bugs. It gives an error when I try to use it.
```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (node:internal/deps/undici/undici:2279:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BingAIClient.sendMessage
```

**Pull request merged**
