### PR TITLE
feat(bing): take a Keyv object instead of options

### PR DESCRIPTION
**Pull request by Erisfiregamer1**
Instead of taking Keyv options (which I had serious troubles with), just take a Keyv object. It's simpler for new Keyv users and is way more intuitive: Just pass your Keyv object as "cache" in the JSON object and do whatever while making it.

### CODE REVIEW

**Comment by Erisfiregamer1** [comment]
I'll fix ESLint later, I'm too tired for this. Plus, I don't see any issues.
@waylaidwanderer Ready for review whenever you get the chance

**Comment by waylaidwanderer** [comment]
@Erisfiregamer1 instead of making it a breaking change, maybe you can add a new option property instead?

**Comment by Erisfiregamer1** [comment]
Which one should take priority? I'm making it the Keyv object.

**Comment by Erisfiregamer1** [comment]
No longer a breaking change; there's a new keyv parameter that overrides "cache". Drop your Keyv store in there and you're ready to go!

@waylaidwanderer Ready for review (again)...

**Comment by waylaidwanderer** [comment]
Thanks @Erisfiregamer1!

**Pull request merged**
